#!/usr/bin/env bash
# Bring up the ephemeral rig: two WooCommerce stores, REST keys, plugin installed.
#
# Idempotent — safe to re-run against a live stack. Writes tests/stack/.env with the
# generated REST credentials so the other scripts (and the e2e test) can read them.
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

SRC_URL="http://src-wp"
TGT_URL="http://tgt-wp"

dc() { docker compose "$@"; }
swp() { dc exec -T src-cli wp --allow-root "$@"; }
twp() { dc exec -T tgt-cli wp --allow-root "$@"; }

echo "==> Building the plugin ZIP (the artifact the target will install)"
( cd ../.. && ./build.sh >/dev/null )
VERSION="$(grep -m1 -oE 'Version:[[:space:]]*[0-9][0-9A-Za-z.-]*' ../../wc-product-sync.php | sed -E 's/^Version:[[:space:]]*//')"
echo "    wc-product-sync-$VERSION.zip"

echo "==> Starting containers"
dc up -d --wait

install_wp() { # install_wp <wp fn> <url> <title>
	local fn="$1" url="$2" title="$3"
	if "$fn" core is-installed 2>/dev/null; then
		echo "    already installed: $url"
		return
	fi
	"$fn" core install --url="$url" --title="$title" \
		--admin_user=admin --admin_password=admin --admin_email=admin@example.invalid \
		--skip-email >/dev/null
	"$fn" plugin install woocommerce --activate >/dev/null
	# WooCommerce refuses to serve products until its pages/tables exist.
	"$fn" wc update >/dev/null 2>&1 || true
	"$fn" option update woocommerce_currency PLN >/dev/null
	echo "    installed: $url"
}

echo "==> Installing WordPress + WooCommerce"
install_wp swp "$SRC_URL" "WPS source"
install_wp twp "$TGT_URL" "WPS target"

# --- REST credentials on the source -------------------------------------------------------
# WooCommerce has no CLI command to mint API keys, so insert one directly. The consumer key
# is stored as a SHA-256 hash (only its truncated form is kept for display), which is why we
# must generate the plaintext here and hand it to the target ourselves — it can never be
# recovered from the DB afterwards.
echo "==> Generating WooCommerce REST keys on the source"
CK="ck_$(openssl rand -hex 20)"
CS="cs_$(openssl rand -hex 20)"
# `wp eval` takes no positional args (that is eval-file), so hand the values over the
# environment — which also keeps them out of the process list and out of any quoting.
dc exec -T -e "WPS_CK=$CK" -e "WPS_CS=$CS" src-cli wp --allow-root eval '
$ck = getenv( "WPS_CK" ); $cs = getenv( "WPS_CS" );
global $wpdb;
$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->prefix}woocommerce_api_keys WHERE description = %s", "wps-e2e" ) );
$wpdb->insert( $wpdb->prefix . "woocommerce_api_keys", array(
	"user_id"         => 1,
	"description"     => "wps-e2e",
	"permissions"     => "read",
	"consumer_key"    => wc_api_hash( $ck ),
	"consumer_secret" => $cs,
	"truncated_key"   => substr( $ck, -7 ),
) );
' >/dev/null

# WooCommerce only accepts key/secret Basic auth when is_ssl() is true; over plain HTTP it
# falls back to OAuth 1.0a, which this plugin does not speak (it sends an Authorization:
# Basic header — wc-product-sync.php:1261). The stack is HTTP-only, so tell the source it is
# behind a TLS-terminating proxy. Site URLs stay http://, so nothing else changes.
echo "==> Forcing is_ssl() on the source (Basic auth over plain HTTP)"
dc exec -T -u 0 src-wp bash -c '
grep -q "WPS_E2E_SSL_SHIM" /var/www/html/wp-config.php || \
sed -i "/That'"'"'s all, stop editing/i \
/* WPS_E2E_SSL_SHIM: make WC accept Basic auth on a plain-HTTP test rig. */\n\$_SERVER[\"HTTPS\"] = \"on\";\n" \
/var/www/html/wp-config.php'

# --- Plugin on the target -----------------------------------------------------------------
echo "==> Installing the plugin on the target from the built ZIP"
twp plugin install "/dist/wc-product-sync-$VERSION.zip" --force --activate >/dev/null
twp option patch update wc_product_sync_options source_url "$SRC_URL" >/dev/null 2>&1 || \
	twp option update wc_product_sync_options \
		"{\"source_url\":\"$SRC_URL\",\"consumer_key\":\"$CK\",\"consumer_secret\":\"$CS\"}" --format=json >/dev/null
twp option patch update wc_product_sync_options consumer_key "$CK" >/dev/null
twp option patch update wc_product_sync_options consumer_secret "$CS" >/dev/null

cat > .env <<EOF
# Generated by tests/stack/up.sh — gitignored.
WPS_SRC_URL="$SRC_URL"
WPS_TGT_URL="$TGT_URL"
WPS_CK="$CK"
WPS_CS="$CS"
WPS_VERSION="$VERSION"
EOF

echo "==> Verifying the target can actually read the source REST API"
CODE="$(dc exec -T tgt-wp curl -s -o /dev/null -w '%{http_code}' \
	-H "Authorization: Basic $(printf '%s:%s' "$CK" "$CS" | base64 -w0)" \
	"$SRC_URL/wp-json/wc/v3/products?per_page=1")"
if [ "$CODE" = "200" ]; then
	echo "    OK: source REST returns 200 to Basic auth"
else
	echo "    FAIL: source REST returned $CODE (expected 200)" >&2
	echo "    Basic auth is being rejected — check the is_ssl() shim above." >&2
	exit 1
fi

echo
echo "Stack up."
echo "  source: http://localhost:8081  (admin/admin)"
echo "  target: http://localhost:8082  (admin/admin)"
echo "  creds:  tests/stack/.env"
